### ISSUE TITLE
Wrong index in for solve_crank_nicholson_heat_equation.m

### ISSUE THREAD

**Issue by XanaDevelops** [mmunar97/21705-LinearAlgebra#1]
At line 34 in [solve_crank_nicholson_heat_equation.m](https://github.com/mmunar97/21705-LinearAlgebra/blob/main/FinalAssignments/1.2.2%20-%20Heat%20(Crank-Nicholson%20scheme)/solve_crank_nicholson_heat_equation.m):

> `    %B(i,i) = ## COMPLETAR ##`

should be :

> `    %B(k,k) = ## COMPLETAR ##`

because is in a for, _line 32_, iterating `k`, not `i`

**Comment by mmunar97** [comment]
You are right. I have just made the change. Thanks for letting me know.
